// lazyload config

var jp_config = {
  easyPieChart:   [ '/static/js/charts/easypiechart/jquery.easy-pie-chart.js' ],
  sparkline:      [ '/static/js/charts/sparkline/jquery.sparkline.min.js' ],
  plot:           [ '/static/js/charts/flot/jquery.flot.min.js', 
                    '/static/js/charts/flot/jquery.flot.resize.js',
                    '/static/js/charts/flot/jquery.flot.tooltip.min.js',
                    '/static/js/charts/flot/jquery.flot.spline.js',
                    '/static/js/charts/flot/jquery.flot.orderBars.js',
                    '/static/js/charts/flot/jquery.flot.pie.min.js' ],
  slimScroll:     [ '/static/js/slimscroll/jquery.slimscroll.min.js' ],
  vectorMap:      [ '/static/js/jvectormap/jquery-jvectormap.min.js', 
                    '/static/js/jvectormap/jquery-jvectormap-world-mill-en.js',
                    '/static/js/jvectormap/jquery-jvectormap-us-aea-en.js',
                    '/static/js/jvectormap/jquery-jvectormap.css' ],
  sortable:       [ '/static/js/sortable/jquery.sortable.js' ],
  nestable:       [ '/static/js/nestable/jquery.nestable.js',
                      '/static/js/nestable/nestable.css' ],
  filestyle:      [ '/static/js/file/bootstrap-filestyle.min.js' ],
  slider:         [ '/static/js/slider/bootstrap-slider.js',
                      '/static/js/slider/slider.css' ],
  chosen:         [ '/static/js/chosen/chosen.jquery.min.js',
                      '/static/js/chosen/chosen.css' ],
  TouchSpin:      [ '/static/js/spinner/jquery.bootstrap-touchspin.min.js',
                      '/static/js/spinner/jquery.bootstrap-touchspin.css' ],
  wysiwyg:        [ '/static/js/wysiwyg/bootstrap-wysiwyg.js',
                      '/static/js/wysiwyg/jquery.hotkeys.js' ],
  dataTable:      [ '/static/js/datatables/jquery.dataTables.min.js',
                      '/static/js/datatables/dataTables.bootstrap.js',
                      '/static/js/datatables/dataTables.bootstrap.css' ],
  footable:       [ '/static/js/footable/footable.all.min.js',
                      '/static/js/footable/footable.core.css' ]
};
